= NTP monitoring configuration for OpenNMS

Configuration tests if the process _ntpd_ is running with detailed longterm data collection.
Long term data collection for delay, offset and jitter in milliseconds.

* _Delay_:  round trip time of queries
* _Offset_: difference between reference time and system clock
* _Jitter_: magnitude of jitter between several time queries

Requirements:

* _ntpd_ should be installed and the command `ntpq -pn` should be executed successfully
* _Net-SNMP_ must be installed and needs permissions to run `ntpq -pn` and the wrapper script `ntpwatch.sh`
* OpenNMS HORIZON/MERIDIAN 1.8+/2015.1.0 using detectors in provisioning requisitions
* OpenNMS 1.6.x users have to use _Capsd_ and it is not possible to have dedicated configuration files.
  It is necessary to merge graph.properties and data collection configuration.

Author: 02/17/2012 <ronny@opennms.org>
License: AGPLv3

== Net-SNMP configuration

. Copy `ntpwatch.sh` from scripts to `/usr/local/bin`
. Extend _Net-SNMP_ configuration to execute the `ntpwatch.sh` wrapper script in `/etc/snmpd.conf`
+
[source, shell]
----
########################################################################
# OpenNMS example - Extending Net-SNMP with user defined scripts
#
# extend [MIBOID] NAME PROG ARGS
extend ntpq_delay '/usr/local/bin/ntpwatch.sh delay'
extend ntpq_jitter '/usr/local/bin/ntpwatch.sh jitter'
extend ntpq_offset '/usr/local/bin/ntpwatch.sh offset'
----
. Restart _Net-SNMP_ with

[source, bash]
----
service snmpd restart

or

systemctl restart snmpd
----

WARNING: Be sure the user context of `snmpd` has permissions to execute `ntpwatch.sh`

== OpenNMS Configuration

. Copy `netsnmp-ntp.xml` to `${OPENNMS_HOME}/etc/datacollection`
. Copy `netsnmp-ntpq.properties` to `${OPENNMS_HOME}/etc/snmp-graph.properties.d`
. Add to `${OPENNMS_HOME}/etc/datacollection-config.xml`
+
[source, xml]
----
<include-collection dataCollectionGroup="Net-SNMP-NTP"/>
----
. restart OpenNMS with

[source, xml]
----
systemctl restart opennms
----

## Process monitoring

. Create a HostResourceSwRunMonitor in `${OPENNMS_HOME}/etc/poller-configuration.xml`
+
[source, xml]
----
<service name="Proc-NTP" interval="300000" user-defined="false" status="on">                                                                 
  <parameter key="retry" value="5"/>
  <parameter key="timeout" value="5950"/>
  <parameter key="port" value="161"/>
  <parameter key="service-name" value="ntpd"/>
</service>

<monitor service="Proc-NTP" class-name="org.opennms.netmgt.poller.monitors.HostResourceSwRunMonitor"/>
----
. Restart OpenNMS with `service opennms restart`
. Assign a detector in Provisioning Requisition for the process ntpd
+
[source, xml]
----
<detector class="org.opennms.netmgt.provision.detector.snmp.HostResourceSWRunDetector" name="Proc-NTP">
  <parameter value="ntpd" key="serviceToDetect"/>
</detector>
----
. Synchronize the Provisioning requisition
